---
name: Tests

on:
  push:
    branches:
      - "mainx"
  pull_request:
    branches:
      - "x*"

jobs:
  tests:
    env:
      MIX_ENV: test
      SPEAKERS_BUILD: true
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Tests on speakers [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        otp: [24.3, 25.1]
        elixir: [1.11.4, 1.12.3, 1.13.4, 1.14.2]
        exclude:
          - otp: 25.1
            elixir: 1.11.4
          - otp: 25.1
            elixir: 1.12.3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Cache hex deps
        id: mix-cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            !_build/*/lib/speakers
          key: ${{ runner.os }}[${{ matrix.otp }}/${{ matrix.elixir }}]-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install prerequisites
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libasound2-dev pkg-config
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        env:
          RUST_BACKTRACE: 1
      - run: mix test
